---
:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :auto_link_deep_dependencies: FALSE
  :build_root: build
  :test_file_prefix: test_
  :which_ceedling: gem
  :default_tasks:
    - test:all

:unity:
  :use_param_tests: TRUE

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - test
    - test/local
  :include:
    - "#{Dir.home}/Downloads/FreeRTOSv10.2.1/FreeRTOS/Source/include"
  :source:
    - src
    - vendor/fake_function_framework
    - "#{Dir.home}/Downloads/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/CMSIS/Include"
    - "#{Dir.home}/Downloads/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/Device/SiliconLabs/EFM32LG"
    - "#{Dir.home}/Downloads/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/Device/SiliconLabs/EFM32LG/Include"
    - "#{Dir.home}/Downloads/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/emlib/inc"
    - "#{Dir.home}/Downloads/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/emlib/src"
    - "#{Dir.home}/Downloads/SimplicityStudio_v4/developer/sdks/gecko_sdk_suite/v2.6/platform/emdrv/**"
    - "#{Dir.home}/Downloads/FreeRTOSv10.2.1/FreeRTOS/Source"
    - "#{Dir.home}/Downloads/FreeRTOSv10.2.1/FreeRTOS/Source/portable/GCC/ARM_CM3"
  :support:
    - test/support
    - test/support/local

:defines:
  :common: &common_defines
  # - EFM32TG232F32
    - EFM32LG232F256
    - TEST
  :test:
    - *common_defines
  :test_preprocess:
    - *common_defines
    - TEST_PREPROCESS

:flags:
  :test:
    :compile:
      :*:
        - -Wall
        - -Wno-int-to-pointer-cast
        - -Wno-pointer-to-int-cast
        - -Wno-overflow

:gcov:
    :html_report_type: basic

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
    - vendor/ceedling_plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov
    - xml_tests_report
    - fake_function_framework
...
